/**
 * Multi-Format Subtitle Exporters & Serializers
 * Supports SRT, WebVTT (.vtt), Advanced SubStation (.ass), and Plain Text (.txt)
 * with Single (Translated/Source) or Bilingual Dual modes.
 */

/**
 * Resolves cue text content based on content mode.
 * @param {object} cue
 * @param {'translated' | 'source' | 'dual'} [contentMode='translated']
 * @returns {string}
 */
export function formatCueText(cue, contentMode = 'translated') {
  if (!cue) return '';

  const source = cue.sourceText ? cue.sourceText.trim() : '';
  const target = cue.targetText ? cue.targetText.trim() : '';

  if (contentMode === 'source') {
    return source;
  }

  if (contentMode === 'dual') {
    if (source && target) {
      return `${source}\n${target}`;
    }
    return target || source;
  }

  // Default 'translated'
  return target || source;
}

/**
 * Converts milliseconds to ASS timestamp "H:MM:SS.cs" (centiseconds, 2 digits)
 * @param {number} ms 
 * @returns {string}
 */
export function msToASSTime(ms) {
  if (typeof ms !== 'number' || isNaN(ms) || ms < 0) {
    return '0:00:00.00';
  }

  const hours = Math.floor(ms / 3600000);
  const remMinutes = ms % 3600000;
  const minutes = Math.floor(remMinutes / 60000);
  const remSeconds = remMinutes % 60000;
  const seconds = Math.floor(remSeconds / 1000);
  const centiseconds = Math.floor((remSeconds % 1000) / 10);

  const pad = (n, w = 2) => String(n).padStart(w, '0');

  return `${hours}:${pad(minutes)}:${pad(seconds)}.${pad(centiseconds)}`;
}

/**
 * Exports subtitle cues to canonical SubRip (.srt) format.
 * @param {Array<object>} subtitles 
 * @param {'translated' | 'source' | 'dual'} [contentMode='translated']
 * @returns {string}
 */
export function exportToSRT(subtitles, contentMode = 'translated') {
  if (!Array.isArray(subtitles) || subtitles.length === 0) return '';

  return (
    subtitles
      .map((cue, idx) => {
        const text = formatCueText(cue, contentMode);
        return `${idx + 1}\n${cue.startTime} --> ${cue.endTime}\n${text}`;
      })
      .join('\n\n') + '\n'
  );
}

/**
 * Exports subtitle cues to WebVTT (.vtt) format.
 * @param {Array<object>} subtitles 
 * @param {'translated' | 'source' | 'dual'} [contentMode='translated']
 * @returns {string}
 */
export function exportToVTT(subtitles, contentMode = 'translated') {
  if (!Array.isArray(subtitles) || subtitles.length === 0) return 'WEBVTT\n\n';

  const formatVTTTime = (srtTime) => srtTime.replace(',', '.');

  const blocks = subtitles.map((cue, idx) => {
    const text = formatCueText(cue, contentMode);
    const start = formatVTTTime(cue.startTime);
    const end = formatVTTTime(cue.endTime);
    return `${idx + 1}\n${start} --> ${end}\n${text}`;
  });

  return `WEBVTT - Exported by Subtitle Wizard\n\n${blocks.join('\n\n')}\n`;
}

/**
 * Exports subtitle cues to Advanced SubStation Alpha (.ass) format.
 * @param {Array<object>} subtitles 
 * @param {'translated' | 'source' | 'dual'} [contentMode='translated']
 * @param {string} [title='Subtitle Wizard']
 * @returns {string}
 */
export function exportToASS(subtitles, contentMode = 'translated', title = 'Subtitle Wizard') {
  if (!Array.isArray(subtitles) || subtitles.length === 0) return '';

  const header = `[Script Info]
; Script generated by Subtitle Wizard
Title: ${title}
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,3,2,2,20,20,30,1
Style: DualSource,Arial,36,&H00E0E0E0,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,2,1,2,20,20,60,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  const dialogueLines = subtitles.map((cue) => {
    const start = msToASSTime(cue.startMs);
    const end = msToASSTime(cue.endMs);
    const text = formatCueText(cue, contentMode).replace(/\r?\n/g, '\\N');
    return `Dialogue: 0,${start},${end},Default,,0,0,0,,${text}`;
  });

  return header + dialogueLines.join('\n') + '\n';
}

/**
 * Exports subtitle cues to Plain Text (.txt) transcript format.
 * @param {Array<object>} subtitles 
 * @param {'translated' | 'source' | 'dual'} [contentMode='translated']
 * @returns {string}
 */
export function exportToTXT(subtitles, contentMode = 'translated') {
  if (!Array.isArray(subtitles) || subtitles.length === 0) return '';

  return (
    subtitles
      .map((cue) => {
        const text = formatCueText(cue, contentMode);
        return `[${cue.startTime.slice(0, 8)} --> ${cue.endTime.slice(0, 8)}]\n${text}`;
      })
      .join('\n\n') + '\n'
  );
}

/**
 * Triggers a browser file download using Blobs.
 * @param {string} content - Serialized text content
 * @param {string} filename - Output filename
 * @param {string} [mimeType='text/plain;charset=utf-8']
 */
export function downloadBlob(content, filename, mimeType = 'text/plain;charset=utf-8') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
